---
- name:  provisioning EC2 instances using Ansible
  hosts: localhost
  gather_facts: False
  
  tasks:
     - name: Task # 1 Launch the new EC2 Instance
       ec2:
          group: "{{ security_group1 }}"
          instance_type: "{{ instance_type1 }}"
          wait: true
          region: "{{ region1 }}"
          keypair: "{{ keypair11 }}"
          image: "{{ ami_id1 }}"
       register: ec2

        
     