---
- name:  provisioning EFS using Ansible
  hosts: localhost
  gather_facts: False
  
  tasks:
     - name: Task # 1 Create EFS file system
       efs:
          name : name1
          encrypt : encrypt1
          performance_mode: mode1
          region: region1
          state: present


       register: efs

        
     