AWSTemplateFormatVersion: "2010-09-09"
Description: An example template for a Step Functions state machine.
Resources:
  MyStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: StateMachineName1
      DefinitionS3Location:
        Bucket: Bucket1
        Key: key1
      RoleArn: RoleArn1
         

